### ISSUE TITLE
Decomposed form of characters

### ISSUE THREAD

**Issue by saadatm** [zeerakahmed/makhzan#15]
The README states that:

> Unicode code points have been chosen in their fully decomposed form.

But in the corpus, various characters are in their precomposed forms, e.g:

* ؤ which is و + ٔ when decomposed, or
* ۂ which is ہ + ٔ when decomposed

An interesting case is ئ (U+0626 ARABIC LETTER YEH WITH HAMZA ABOVE), which is  ي + ٔ (U+064A ARABIC LETTER YEH plus U+0654 ARABIC HAMZA ABOVE​) in its decomposed form. However, U+064A is usually used for Arabic and thus not found on most Urdu keyboards. Another thing is this recommendation from the Unicode standard in [section 9.2 Arabic > Combining Hamza > Combining Hamza above](https://www.unicode.org/versions/Unicode13.0.0/ch09.pdf#page=29):

> Because U+0626 is canonically equivalent to the sequence <U+064A ARABIC LETTER YEH, U+0654 ARABIC HAMZA ABOVE>, when U+0654 is applied to U+064A ARABIC LETTER YEH, the _yeh_ should lose its dots in all positional forms, even though _yeh_ retains its dots when combined with other marks.

Depending on the underlying shaping engine, this may or may not happen. So, for example, in Noto Nastaliq Urdu, the word کئی and its fully decomposed form کئی will render like this for Uniscribe and HarfBuzz:

![image](https://user-images.githubusercontent.com/6615143/94305678-02290080-ff8b-11ea-8462-4d1b6ad44df4.png)

The incorrect rendering (with the dots) of the fully decomposed form will be alien to most Urdu readers, and they may blame it on the corpus even though it's the shaping engine that is not following Unicode's recommendation.

**Comment by zeerakahmed** [comment]
Very interesting!

Where we are not decomposing, when we said we should have, we should correct. You have raised an interesting argument however, about whether we should decompose at all.

The primary rationale for decomposition was that it allowed an easier way to remove diacritics and deal with the smallest atomic unit of Unicode characters when performing analyses. You can see the sort of operations we run through the API of the [Naqqash library](http://github.com/zeerakahmed/naqqash) (which we also use to clean text in Makhzan). 

In some text input mechanisms, such as text fields in iOS, decomposed characters are automatically precomposed on input. Which suggested that leaving characters decomposed may not be a bad tradeoff. This was also supported by the fact that the primary goal of Makhzan is analysis and processing, as opposed to representation. 

I feel that all code points should be either fully precomposed or fully decomposed. What are your thoughts?

**Comment by saadatm** [comment]
> This was also supported by the fact that the primary goal of Makhzan is analysis and processing, as opposed to representation.

Yes, and decomposed forms indeed make sense for Makhzan. [Relevant bit](https://www.unicode.org/faq/normalization.html#2) from Unicode FAQ on normalization:

> The choice of which [normalization] to use depends on the particular program or system. NFC is the best form for general text, since it is more compatible with strings converted from legacy encodings. NFKC is the preferred form for identifiers, especially where there are security concerns (see [UTR #36](http://www.unicode.org/reports/tr36/)). NFD and NFKD are most useful for internal processing.

I personally prefer fully precomposed (with some exceptions like the word _allah_, as discussed in #14), but that is for general text (as the FAQ entry notes). For Makhzan's intended use case, fully decomposed forms are reasonable and practical, but that also means a cleaning first step (using Naqqash) to ensure that fully decomposed forms are indeed being used.

The shaping engine bugs (like the one I mentioned earlier) are peculiar and interesting, but perhaps they can be elaborated in the README so that the intended audience of researchers etc. know what to expect.

**Comment by zeerakahmed** [comment]
Agreed, we should add that we intend to use NFD normalization, with potential implications given the status of current fonts to the README. @htalat has noted in #18 that we should automate the decomposition on every addition of text.

**Comment by zeerakahmed** [comment]
Updated documentation: https://github.com/zeerakahmed/makhzan/blob/master/docs/markup.md
