### ISSUE TITLE
Explore Github Actions

### ISSUE THREAD

**Issue by htalat** [zeerakahmed/makhzan#18]
Context:
> That makes sense. There are a few things that we could build here:
>1. Every time new files are added run the preprocessor
>2. Make sure all files are valid xml
>3. Run stats every text files or scripts are modified

_Originally posted by @zeerakahmed in https://github.com/zeerakahmed/makhzan/pull/9#issuecomment-662874029_

- [x]  Basic setup of Github actions
- [x]  script/program for checking if files are valid xml
- [x] ability to run scripts based on an event e.g. new file added in a certain directory => run swift scripts + file-as-a-db that should reside in `tools\` dir
- [x] list all other scenarios/events which we can leverage => [Events that trigger workflow](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)

**Comment by zeerakahmed** [comment]
Yes – I think we should also add to this the common replacements generated in the wordBreakingValidator script. Over time this may grow.

Thanks for adding this here.

**Comment by rohan2734** [comment]
hi i would like to setup basic github actions, could you assign me this task?

**Comment by htalat** [comment]
Thanks @rohan2734! Most of the scripts are written in swift. See if we can support that too!

**Comment by rohan2734** [comment]
@htalat  actually idk swift or python, i just want to setup basic github actions
i am good at react , react-native and js.  do you think i would be able to do that

**Comment by rohan2734** [comment]
What are things do we need to know for setting up basic github actions?

**Comment by htalat** [comment]
You actually don't have to know python or swift. You'd just have to ensure we can run the scripts like `python <filename>` & similarly for swift.

As for github actions, you can checkout their [documentation](https://docs.github.com/en/free-pro-team@latest/actions) or search for them on the web :)

**Comment by htalat** [comment]
@zeerakahmed [this](https://github.com/htalat/makhzan/runs/1202048890?check_suite_focus=true) seems great! python & swift available.

I was thinking to setup a cron job as a trigger (or have the option to run manually too) and have a file-as-a-db to keep state if we have to and run any script we want. What do you think?

**Comment by zeerakahmed** [comment]
Should we run it every time we commit? Or do we need a cron job?

**Comment by htalat** [comment]
Commit works too if almost of them are data uploads, which I'm assuming they are ...  since this is the corpus. *ba dum tss*

**Comment by zeerakahmed** [comment]
Ha – can we do it when data changes in specific directories? We don't want
to run it when documentation, scripts or stats are updated.

**Comment by htalat** [comment]
yeah we can check at the start of every script via the file-as-a-db (to maintain state) whether to go ahead  to process or not

**Comment by zeerakahmed** [comment]
Let’s configure that! 

For now let’s look for changes in the `/text` directory. 

And when changes are made let’s run the preprocessor? And we can add xml validation to the preprocessor. 

Will this action run on the developers’ local machine or on github servers?

Zeerak.

On Oct 3, 2020, at 2:00 AM, Hassan Talat <notifications@github.com> wrote:

﻿
yeah we can check at the start of every script via the file-as-a-db (to maintain state) whether to go ahead to process or not

**Comment by htalat** [comment]
Github’s server. So it’ll run whenever we commit to master branch

**Comment by zeerakahmed** [comment]
Sounds great!

**Comment by htalat** [comment]
Well, here's a [test run!](https://github.com/htalat/makhzan/runs/1213259206?check_suite_focus=true)! 

dw, put in a bad xml file on purpose.

<img width="687" alt="Screenshot 2020-10-05 at 11 37 59 PM" src="https://user-images.githubusercontent.com/13875558/95167164-01028b00-0764-11eb-8dfd-b5bcf4584345.png">

Here's the [repo diff](https://github.com/htalat/makhzan/pull/1).

**Comment by zeerakahmed** [comment]
Awesome! And this is just the preProcessor spitting out that error message?

**Comment by htalat** [comment]
yes, I added a print statement `Processing file...` and added a bad file to a testing folder `tex`

**Comment by zeerakahmed** [comment]
Awesome sounds great! Can we change that print statement to only print when
the xml is bad?
There are thousands of files now so the printing would be enormous.

And then we should just add this to the main repo!

**Comment by htalat** [comment]
sure!

**Comment by zeerakahmed** [comment]
🙌🏽
