### ISSUE TITLE
Some files have invalid xml.

### ISSUE THREAD

**Issue by arkhalid** [zeerakahmed/makhzan#28]
The following files have invalid XML:
0013.xml
0044.xml
5358.xml
5390.xml

For example, consider the file 0013.xml:

> <document>
	<meta>
		<title>معاشرہ کی اصلاح کے وسائل</title>
		<author>
			<name>امام امین احسن اصلاحی</name>
			<gender>Male</gender>
		</author>
		<publication>
			<name>Mahnama Ishraq January 2014</name>
			<year>2014</year>
			<city>Lahore</city>
			<link>https://www.javedahmedghamidi.org/#!/ishraq/5adb7349b7dd1138372dbb5a?articleId=5adb7364b7dd1138372dbe1a&amp;year=2014&amp;decade=2010</link>
			<copyright-holder>Al-Mawrid</copyright-holder>
		</publication>
		<num-words>1910</num-words>
		<contains-non-urdu-languages>No</contains-non-urdu-languages>
	</meta>
	<body>
	<heading>معاشرہ کی اصلاح کے وسائل</heading>
	<section>
		<p>اصلاح معاشرہ کے جن پہلوؤں کی طرف ہم نے توجہ دلائی ہے، بہت سے درد مندوں نے ان کی اہمیت محسوس کی ہے۔ اس اثنا میں ہمیں جو خطوط موصول ہوئے ہیں، ان سے اندازہ ہوتا ہے کہ ایسے لوگ بحمد اللہ ہمارے اندر موجود ہیں جو صورت حال کی نزاکت کا احساس رکھتے ہیں اور دین کے بقا و تحفظ کے لیے وہ اپنا وقت بھی صرف کرنے کے لیے تیار ہیں اور ان میں سے جن کو خدا نے مال دیا ہے، وہ اپنا مال بھی خرچ کرنے کے لیے آمادہ ہیں۔ ان خطوط سے ہمیں بڑی تقویت حاصل ہوئی ہے۔ ہماری دعا ہے کہ اللہ تعالیٰ ایسے درد مندوں کی تعداد میں اضافہ فرمائے۔</p>
		<p>کسی معاشرہ کے اندر ہزار خرابیاں موجود ہوں، لیکن جب تک اس کے اندر ان خرابیوں کو محسوس کرنے والے اور ان کو دور کرنے کی راہ میں ایثار کرنے والے افراد موجود رہیں، اس وقت تک اس کے مستقبل کی طرف سے مایوس ہونے کی کوئی وجہ نہیں ہے۔ کسی معاشرہ کی حالت مایوس کن اس وقت ہوتی ہے، جب اس کا بگاڑ اس حد کو پہنچ جائے کہ نہ اس کی اصلاح کے لیے اپنا وقت اور مال قربان کرنے والے باقی رہ جائیں اور نہ اس کی حالت پر غم کھانے والے۔ الحمد للہ ہمارا بگاڑ ابھی اس حد کو نہیں پہنچا ہے۔</p>
		<p>لیکن ان خطوط سے جہاں ہمیں یہ اندازہ کر کے خوشی ہوئی ہے کہ ہمارے اندر ایسے لوگ موجود ہیں جو اپنے وسائل و ذرائع اسلام کے لیے استعمال کرنے پر آمادہ ہیں۔ وہیں انھی خطوط سے ہمیں یہ اندازہ بھی ہوا ہے کہ ابھی اس معاملہ کے بعض گوشے لوگوں کے سامنے اچھی طرح واضح نہیں ہیں۔ ہمارا خیال یہ ہے کہ جب تک یہ گوشے اچھی طرح واضح نہیں ہوں گے، اس وقت تک یہ احساس، جس کی طرف ہم نے اشارہ کیا ہے، کوئی مفید نتیجہ نہیں پیدا کر سکتا۔ اس وجہ سے یہ ضروری معلوم ہوتا ہے کہ ہم ان پہلوؤں کی طرف بھی چند سطروں میں توجہ دلا دیں۔</p>
		<p>اس وقت جو لوگ اس مقصد کے لیے اپنے مال یا وقت کی کوئی قربانی دینا چاہتے ہیں، انھیں دو باتوں پر اچھی طرح غور کر کے اپنے ذہن کو یک سو کر لینا چاہیے۔</p>
		<p>ایک اس بات پر کہ اس وقت اسلام کے لیے جو مرحلہ درپیش ہے، اس مرحلہ میں اسلام کی خدمت کے لیے سب سے مقدم اور سب سے زیادہ ضروری کام کیا ہے؟ دوسرے اس بات پر کہ اس وقت جو وسائل و ذرائع میسر ہیں، ان کو اس مقدم اور ضروری کام کے لیے زیادہ سے زیادہ بہتر طریقہ پر کس طرح استعمال کیا جا سکتا ہے؟</p>
		<p>ان دونوں سوالوں پر غور کیے اور ان کے باب میں یک سو ہوئے بغیر جو کام اس وقت کیے جائیں گے، ہمیں اندیشہ ہے کہ ان پر ہماری مادی و ذہنی طاقتیں تو صرف ہوں گی، لیکن ان سے کوئی فائدہ نہیں ہو گا اور ہو گا تو اتنا کم کہ وہ نہ ہونے کے برابر ہو گا۔</p>
		<p>پہلے سوال پر غور کرنے کی ضرورت اس وجہ سے ہے کہ یہ بات تو بہت سے لوگ جانتے ہیں کہ ہمارا معاشرہ بیمار ہے، لیکن اس امر میں بڑا اختلاف ہے کہ یہ بیماری کیا ہے اور اس کا علاج کیا ہے؟ اس بیماری اور اس کے علاج کے متعین نہ ہونے کے سبب سے ہر تیماردار الگ الگ مرض تشخیص کر رہا ہے اور الگ الگ اس کے علاج تجویز کر رہا ہے۔ بعض لوگ اس کے ہاتھ پاؤں کو مریض سمجھ رہے ہیں اورا پنی اس تشخیص کے مطابق اس کے پاؤں پر مالش کرنا چاہتے ہیں۔ بعض اس کے پیٹ میں درد خیال کر رہے ہیں اور اپنی سمجھ کے مطابق اس درد کی تسکین کی کوئی دوا دینا چاہتے ہیں۔ بعض اس کو ضعف قلب کا مریض سمجھتے ہیں، وہ اس ضعف قلب کو دور کرنے کے لیے کوئی مقوی قلب چیز اس کو کھلانا چاہتے ہیں۔ غرض جتنے تیماردار ہیں، اتنی ہی تشخیصیں اور اتنے ہی علاج ہیں۔ یہ اختلاف تشخیص و اختلاف علاج اگرچہ زیادہ تر نتیجہ ہے اس ذہنی پریشانی کا جس سے ایک ہمہ گیر خرابی کے احساس نے ہمیں دوچار کر دیا ہے اور اس پہلو سے یہ ایک قدرتی سی چیز ہے، لیکن کسی موثر اور نتیجہ خیز علاج کے لیے اس پریشان خیالی کا دور ہونا ضروری ہے۔ جب کسی گھر میں آگ لگتی ہے تو بالعموم یہی ہوتا ہے کہ جس جس کونے سے بھی دھواں اٹھتا نظر آتا ہے، پاس پڑوس کے ہمدرد اسی کونے کو آگ کا مرکز سمجھ کر اس پر اپنے اپنے پانی کے ڈول پھینکنے شروع کر دیتے ہیں۔ یہ کام اگرچہ وہ ازراہ ہمدردی کرتے ہیں، لیکن منتشر کوششوں سے آگ نہیں بجھا کرتی۔ آگ بجھتی اس وقت ہے جب فائر بریگیڈ آگ کے اصل سنٹر کو متعین کر کے اس کو اپنے محاصرے میں لے لیتا ہے اور اپنے زور دار دونگڑوں سے اس کے سر غرور کو کچل کے رکھ دیتا ہے۔</p>
		<p>دوسرے سوال پر غور کرنے کی ضرورت یوں ہے کہ اس مقصد کے لیے جو اسباب و وسائل اس وقت میسر ہیں یا آئندہ جن کے میسر آنے کی توقع ہے، وہ بہرحال نہایت محدود بھی ہیں اور نہایت منتشر حالت میں بھی ہیں۔ اگر یہ اسباب و وسائل الگ الگ مختلف مقامات پر استعمال ہوں تو کہیں بھی ان سے کوئی بڑے پیمانہ کا کوئی ایسا نتیجہ خیز کام نہیں انجام پا سکتا جو اس ضرورت کو پورا کر سکے جس کو پورا کرنا پیش نظر ہے۔ پھر مادی وسائل سے زیادہ اہم سوال اس مقصد کے لیے ذی صلاحیت اور موزوں اشخاص کی فراہمی ہے۔ اس زمانہ میں کسی اس طرح کے کام کے لیے سرمایہ حاصل کرنا جتنا مشکل ہے، اس سے کہیں زیادہ مشکل اس کے لیے اس دور قحط الرجال میں آدمیوں کی تلاش ہے۔</p>
		<p>ان دونوں سوالوں میں سے جہاں تک پہلے سوال کا تعلق ہے، اس پر ہم نے جس حد تک غور کیا ہے ہم اسی نتیجہ پر پہنچے ہیں کہ ہماری بیماری کوئی سرسری اور معمولی قسم کی نہیں ہے، بلکہ بڑی گہری ہے۔ انگریزوں کے تسلط کے بعد سے مغربی فکر و فلسفہ کی جو چھوت ہمیں لگی، اس نے ڈیڑھ دو سو سال کی مدت میں ایک مزمن بیماری کی شکل اختیار کر لی ہے اور اب اس نے ہمارے ذہین طبقہ کے دماغ اور دل بالکل ماؤف کر دیے ہیں۔ اس بیماری کا عمل تقریباً یک طرفہ قسم کا رہا ہے۔ اس کے تدارک کی تدبیریں یا تو اختیار ہی نہیں کی گئیں یا اختیار کی گئیں تو وہ اتنی سائنٹیفک اور علمی نہیں تھیں جتنا سائنٹیفک اور علمی اس کا عمل تھا، اس وجہ سے آہستہ آہستہ اس کے اثرات دماغوں اور دلوں کے اندر اتنے گہرے اتر چکے ہیں کہ اب اس حقیقت کا اعتراف کرنا پڑتا ہے کہ ان سے ہمارے ذہین طبقہ کی اکثریت کے عقائد و ایمانیات کی جڑیں تک ہل چکی ہیں۔ ظاہر ہے کہ کسی قوم کے ذہین طبقہ کی بیماری اعضا و جوارح کی بیماری نہیں ہے، بلکہ اس کے دماغ اور عقل کی بیماری ہے اور دماغ کی خرابی ہر شخص سمجھ سکتا ہے کہ ایک ایسی بیماری ہے جس کا علاج نہ تو درد سر کی دوا سے ہو سکتا ہے اور نہ ہر عطائی اس کا علاج کر سکتا ہے۔</p>
		<p>یہ مغرب کی فاسد عقلیت کا ایک عذاب ہے جو ہم پر مسلط ہوا ہے۔ اس فاسد عقلیت کا مداوا اگر ہو سکتا ہے تو اس صالح عقلیت ہی سے ہو سکتا ہے جو قرآن اور سنت کی حکمت کے اندر مضمر ہے۔ ظاہر ہے کہ یہ کام ہر شخص کے بس کا نہیں ہے۔ یہ کام وہی لوگ کر سکتے ہیں جو دین کی عقلیت کے بھی رازداں ہوں اور جو موجودہ عقلیت کے مفاسد سے بھی اچھی طرح واقف ہوں اور ساتھ ہی اس معیار و پیمانہ پر اور اس انداز اور اس طریقہ سے اس کام کو کر سکنے کا سلیقہ رکھتے ہوں جو موجودہ زمانہ میں اس طرح کے کام کے لیے وجود میں آ چکا ہے۔ یہ ایک ٹھوس علمی اور تحقیقی کام ہے جس کا فائدہ صرف اسی صورت میں حاصل ہو سکنے کی توقع ہے جب ایک ٹیم پرسکون ماحول اور اطمینان بخش حالات کے اندر اس خدمت کے لیے اپنے آپ کو دوسری تمام دل چسپیوں اور ہنگامی مشاغل سے فارغ کر لے اور اپنی محنتوں سے ان تمام زہروں کے تریاق بھی فراہم کرے جن سے اس وقت ہمارے معاشرے کا ذہین طبقہ مسموم ہے اور ساتھ ہی ان لوگوں کی تربیت بھی کرے، جو آئندہ نسلوں کے لیے اس خدمت کو جاری رکھ سکیں۔</p>
		<p>دوسرے سوال سے متعلق ہمارا مشورہ اسلام اور مسلمانوں کے ان تمام بہی خواہوں کے لیے جو اس عظیم خدمت میں اپنے وسائل و ذرائع سے حصہ لینا چاہتے ہیں یہ ہے کہ وہ اسلام کے وسیع مفاد کے پیش نظر اپنے شخصی اور مقامی میلانات و رجحانات کو اس وقت بھول جائیں۔ پیش نظر کام ایک بڑا وسیع کام ہے، اس کو صحیح طور پر انجام دینے کے لیے وسیع اسباب و وسائل کی ضرورت ہے جن کے فراہم ہونے کی توقع صرف اسی شکل میں ہو سکتی ہے جب تمام اصحاب وسائل مل کر اپنی متحدہ کوشش سے فراہم کریں۔ متحدہ کوشش کی صورت میں تو بلاشبہ اس بات کی توقع ہے کہ اس کام کے لیے ضرورت کے مطابق سرمایہ بھی حاصل ہو جائے اور اس کا بھی امکان ہے کہ اس کام کو چلانے کے لیے موزوں اشخاص بھی مل جائیں۔ لیکن اگر وسائل رکھنے والے حضرات کسی ایک اسکیم پر متفق نہ ہو سکے تو اس صورت میں کسی بڑے کام کے انجام پا سکنے کی کوئی توقع نہیں ہے۔ زیادہ سے زیادہ بس یہ ہو سکے گا کہ بعض لوگ اپنے اپنے شہروں میں ایک آدھ بے مقصد قسم کے مدرسے اور قائم کر دیں گے یا اپنے دیہاتوں میں وعظ کہنے کے لیے ایک آدھ مبلغ بھیج دیں گے۔ اس سے ان مدرسوں کے بانیوں اور ان مبلغوں کے سرپرستوں کو تو ضرور تسلی ہو جائے گی کہ انھوں نے دین کی کوئی خدمت انجام دی ہے، لیکن ان مدرسوں اور ان مبلغوں سے اس اسلام کا کیا بھلا ہو گا جس کی بنیادیں تک ہمارے معاشرے کے اندر ہل چکی ہیں۔</p>
		<p>اس کام کے ساتھ ساتھ یہ بھی ضروری ہے کہ اپنے عام معاشرہ کی دینی و اخلاقی اصلاح کی جدوجہد بھی شروع کی جائے۔ اس کا زوال و انحطاط اب خطرہ کے پوائنٹ تک پہنچ چکا ہے۔ اب اس کام میں مزید غفلت کے معنی اس کو اسلامی نقطۂ نظر سے موت کے حوالہ کر دینے کے ہوں گے۔ ابھی تو اس بات کا امکان ہے کہ اگر سمجھ دار بے لوث اور مخلص لوگوں کی ایک جماعت اس کی اصلاح کے لیے اٹھ کھڑی ہو تو شاید اللہ تعالیٰ اس کی کوششوں سے اس کی حالت کو سنبھال دے، لیکن اگر یہ کوشش نہ کی گئی تو زیادہ عرصہ نہیں گزرے گا کہ اس کے لیے گمراہی کا ہر موڑ مڑ جانا بالکل متوقع ہو گا اور عند اللہ اس کی ذمہ داری ان لوگوں پر ہو گی جو اس کی اصلاح کے سلسلہ میں کچھ کر سکنے کی صلاحیت رکھتے تھے، لیکن انھوں نے کچھ نہیں کیا۔ جن لوگوں کے نزدیک سیاسی اقتدار کے حصول کے بغیر اصلاح معاشرہ کی کوئی جدوجہد ممکن ہی نہیں ہے، انھیں ہم ان کے نظریے کی بنا پر مجبور سمجھتے ہیں، لیکن جو لوگ سیاست سے الگ رہ کر بھی اسلام کی خدمت کر سکنے کے امکانات کے قائل ہیں، ہم انھیں ان کی ذمہ داری یاد دلانا چاہتے ہیں۔</p>
	</section>
</document>

This file is missing the closing tag for body.

**Comment by zeerakahmed** [comment]
Thanks for the report! We'll fix this asap.
We now have a CI pipeline that should catch this as we add new files courtesy @htalat.

**Comment by htalat** [comment]
5427.xml too from the looks of it.
https://github.com/zeerakahmed/makhzan/runs/1399516991?check_suite_focus=true

<img width="547" alt="Screenshot 2020-12-15 at 7 51 51 PM" src="https://user-images.githubusercontent.com/13875558/102230772-17208a80-3f0f-11eb-891d-e7d570ac2d25.png">

**Comment by zeerakahmed** [comment]
Thanks for fixing this @htalat.
