### ISSUE TITLE
Zero width non joiner in the dataset

### ISSUE THREAD

**Issue by adelra** [zeerakahmed/makhzan#3]
Hi, 

Great job on the dataset, my question is that does it include zero-width non-joiner?

**Comment by zeerakahmed** [comment]
Thank you!
Much of our source text has not used it, but we are in the process of correcting and standardizing usage of the zero-width non-joiner.

**Comment by adelra** [comment]
Are there any publicly available datasets for Urdu that has ZWNJ correctly used in them?

**Comment by zeerakahmed** [comment]
Not that I'm aware of
