### ISSUE TITLE
CI Workflow Failure

### ISSUE THREAD

**Issue by zeerakahmed** [zeerakahmed/makhzan#33]
CI workflow seems to be unable to build Naqqash and hence fails to proceed.

**Comment by zeerakahmed** [comment]
@htalat could you take a look when you have a chance?

**Comment by htalat** [comment]
Will do.

**Comment by zeerakahmed** [comment]
Thanks! 

On May 12, 2021, at 1:09 AM, Hassan Talat ***@***.***> wrote:

﻿
Will do.
