### ISSUE TITLE
Citation information?

### ISSUE THREAD

**Issue by albertvillanova** [zeerakahmed/makhzan#43]
What is the citation information of the dataset?

Thank you.

**Comment by zeerakahmed** [comment]
Each file in the `/text` folder contains citation information in the `<meta>` tag. 

Hope this helps!

**Comment by zeerakahmed** [comment]
Unless you are asking about how to cite the dataset as a whole?

**Comment by albertvillanova** [comment]
Yes, I wanted to refer the dataset as a whole.

**Comment by zeerakahmed** [comment]
For the moment, I'll format as below:

@misc{makhzan,
      title={Maḵẖzan},
      howpublished = "\url{https://github.com/zeerakahmed/makhzan/}",
}

**Comment by zeerakahmed** [comment]
Please reopen if needed!

**Comment by albertvillanova** [comment]
Thanks, @zeerakahmed. 

We have added that information to the Hugging Face Datasets library:
- https://github.com/huggingface/datasets/pull/4894

**Comment by zeerakahmed** [comment]
Thank you @albertvillanova!
